### ISSUE TITLE
Stopping Cloud Controllers during PCF backup window causing applications unresponsive?

### ISSUE THREAD

**Issue by Akhilesh-Anb** [pivotalservices/cfops#111]
Hi team,

We need your help in providing solution to below mentioned issues.

We have PCF foundations version of OM-1.7.20 & ERT-1.7.35
We take daily backups of our PCF environments during a certain time.
we have 3 AZs and we have Cloud Controller & Cloud Controller Workers in each AZ. Will this cfops automated backup will bring all cloud controllers down?

As our cloud controllers are stopped and started during that window, app teams are complaining about unavailability of service. 

Will the backup causes unavailability of app?

Appreciate your help

Thanks,
Akhilesh Appana

**Comment by eamonryan** [comment]
Hi Akhilesh,

As stated on the main page:
`Backing up ER will take Cloud Controller offline for the duration of the backup, causing your foundation to become readonly for the duration of the backup. App pushes etc will not work during this time.`

So yes, `cfops` will take down your Cloud Controllers until backup is complete. Your running apps will not become unavailable - they will still be accessible to end-users, but new apps will be temporarily unable to be pushed and existing apps will temporarily be unable to be changed (started/stopped/scaled etc.) until the cloud controllers are back online.

If this is a problem for your team, then I'd recommend changing your backup window to a less busy time of day. Stopping the Cloud Controllers is necessary to capture a consistent state of the environment, otherwise changes could be missed or captured in an inconsistent fashion.

Cheers,
Éamon
