### ISSUE TITLE
Feature request:  Add support for connecting via ssh key instead of tempest password

### ISSUE THREAD

**Issue by mdcarlson** [pivotalservices/cfops#31]
Customer has requested that cfops support logging into Ops Manager tempest user using a specified ssh key rather than password.  This will also better support AWS installations which limit ssh access to keypairs by default.

**Comment by mdcarlson** [comment]
Note:  There was no "tempest" user on the AWS AMI for Ops Manager 1.5.0.   Creating user on the Ops Man VM allowed the Ops Man action to succed.

**Comment by xchapter7x** [comment]
cfops is only tested against vsphere installations. while there are plans to make it support aws and openstack installs of PivotalCF, this is not yet an available feature.

even with ssl key support you would still not be able to run this on aws in its current form, at least not to backup the Elastic Runtime. This is due to how we dump the internal foundation databases.
we will make note of the full aws support request, add it to our backlog and work on adding in this functionality when we can.

**Comment by mdcarlson** [comment]
Sounds good.   The previous version (0.6.x) did run to completion on an AWS PCF installation, but we didn't verify that the ERS content was correct.

We'll be glad to help test when you have an initial version of AWS or OpenStack support.
