### ISSUE TITLE
Restore fails for CCDB database

### ISSUE THREAD

**Issue by vmking** [pivotalservices/cfops#58]
Our CFOPS restore fails "Process exited with: 1. Reason was:  ()"  

I can provide more information and flavor around this problem if needed.

**Comment by ParkerFleming** [comment]
@vmking please re-attach your scrubbed logs so we can investigate.

**Comment by xchapter7x** [comment]
can you please provide:
- the cfops version
- pcf version
- iaas in use
- cfops command executed


thanks.

**Comment by vmking** [comment]
Attached are the scrubbed logs. 

The CFOPS version is 2.0.87
PCF 1.5.0 OPS Managers and 1.5.3 ERT
Vsphere ESXi 5.5

./cfops backup --opsmanagerhost 10.23.10.35 --adminuser administrator --adminpass  --opsmanageruser ubuntu --opsmanagerpass  --destination /users/kevin.doyle/Downloads/CFOM1/ --tile ops-manager


./cfops backup --opsmanagerhost 10.23.10.35 --adminuser administrator --adminpass  --opsmanageruser ubuntu --opsmanagerpass  --destination /users/kevin.doyle/Downloads/CFOM2/ --tile elastic-runtime


./cfops restore --opsmanagerhost 10.23.10.35 --adminuser administrator --adminpass  --opsmanageruser ubuntu --opsmanagerpass  --destination /users/kevin.doyle/Downloads/CFOM1/ --tile ops-manager


./cfops restore --opsmanagerhost 10.23.10.35 --adminuser administrator --adminpass  --opsmanageruser ubuntu --opsmanagerpass  --destination /users/kevin.doyle/Downloads/CFOM2/ --tile elastic-runtime
[CFOPS Log1.pdf](https://github.com/pivotalservices/cfops/files/186538/CFOPS.Log1.pdf)

**Comment by xchapter7x** [comment]
Im still not clear what you're saying the issue is.

the log file you attached shows a successful restore of elastic-runtime

**Comment by vmking** [comment]
This particular piece below leads me to believe the CCDB restore was not successful unless Process exited with 1 means successful now. And after running this restore we get Error 500 trying to login to the platform either through the UI, or the CLI

pgdump restore called: %!(EXTRA
[]string=[PGPASSWORD=2d6d375c1c23d373 /var/vcap/
packages/postgres/bin/pg_restore -h localhost -U
vcap -x -p 2544 -c -d ccdb /tmp/archive.backup],
*ssh.ExitError=Process exited with: 1. Reason
was: ())

**Comment by xchapter7x** [comment]
actually exit code 1 does mean great success :)
sorry, i missed that error. PDF is a little hard to grep for me. 

anyways, what that error is saying is that when that exact command was run on the ccdb box the exit code was 1, which you probably know already. 

I would take the following approach: 
- Manually validate the ccdb backup file is not corrupt. You can convert it from the binary format locally and just cat it to see the contents.
- Manually run that command (cut and paste) when ssh'd into the ccdb VM
- I would try upgrading cfops, newer versions contain work in this area due to the products switch to using mariadb instead of postgres.

These should help you get to the bottom of what your issue is.

As for the error 500 on login, not sure what would be causing that. CCDB is separate from login functionality. That would more be a UAADB function and I didnt see errors on that. Regardless, I also dont think you would see a 500 even if there is a DB issue w/ cloud controller. That sounds like possibly something separate. What exactly are you doing/running to get the 500? Have you called PivotalCF Support?

**Comment by xchapter7x** [comment]
has this been resolved?
