### ISSUE TITLE
Stemcells are not restored

### ISSUE THREAD

**Issue by ebornier-pivotal** [pivotalservices/cfops#77]
Hi,

Stemcells imported into ops manager are not restored after a backup / restore process from scratch (with a fresh new ops manager).

Erwan Bornier

**Comment by xchapter7x** [comment]
cfops backup/restore for ops manager simply automates the import/export functionality available in the ops manager web UI. This is simply how ops manager functions. 

I believe the reason for this is, restore is intended just to restore the ops manager config. It is likely that the restore is being done from a archive generated on a different version of ops manager. As such it would require a different stemcell potentially.

We do have a spike to explore backing up / restoring the director vm and with it, the bosh blobstore & db. This would restore the state of the available stemcells as that is where they are stored. This should address the stemcell issue you are raising.

Again, this is simply how ops manager import/export works. Since we merely automate that via a cli utility, there isnt any issue to be resolved here.

I will keep you posted on the Director VM backup/restore functionality mentioned above.

**Comment by ebornier-pivotal** [comment]
Hi John,

Thanks you for your feedback.

Yes, my request was more an enhancement than an issue. It was expressed by
my customer (Renault) during a ops dojo, it was perceived like something
missing.

Happy to know that this could be address by a more global user story.

My request was in the context of disaster recovery with a ops manager
recreation from scratch -- same ops manager version.

Regards,

Erwan

On Tue, Apr 26, 2016 at 9:24 AM, John Calabrese <notifications@github.com>
wrote:

> cfops backup/restore for ops manager simply automates the import/export
> functionality available in the ops manager web UI. This is simply how ops
> manager functions.
>
> I believe the reason for this is, restore is intended just to restore the
> ops manager config. It is likely that the restore is being done from a
> archive generated on a different version of ops manager. As such it would
> require a different stemcell potentially.
>
> We do have a spike to explore backing up / restoring the director vm and
> with it, the bosh blobstore & db. This would restore the state of the
> available stemcells as that is where they are stored. This should address
> the stemcell issue you are raising.
>
> Again, this is simply how ops manager import/export works. Since we merely
> automate that via a cli utility, there isnt any issue to be resolved here.
>
> I will keep you posted on the Director VM backup/restore functionality
> mentioned above.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/pivotalservices/cfops/issues/77#issuecomment-214801118>
>



-- 
Erwan Bornier | Cloud Platform Architect, Southern EMEA | Pivotal
+33 6 62 23 31 90 | ebornier@pivotal.io

**Comment by matthewcosgrove** [comment]
Just going through this with a customer, and wanted to propose that there is potential approach which is scriptable and could therefore be incorporated into cfops. Essentially, as I understand it, we need to trick (is 'educate' a better word?) OpsManager into believing this is a fresh install. This can be achieved by deleting the following file from the OpsManager VM prior to clicking Apply Changes

/var/tempest/workspaces/default/deployments/bosh-state.json
